import gymnasium as gym
import numpy as np
import pygame
class TicTacToe(gym.Env):
    def __init__(self):
        self.state = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    def step(self, action):
        ...
    def reset(self):
        ...
    def render(self, mode='human'):
        ...
    def close(self):
        ...
    def seed(self, seed):
        ...
    def action_handler(self):
        ...
